name: test2
env:
  APP_NAME: devops-company-site
  ENVIRONMENT: development
  COMPANY: CloudNova
 
on:
  push:
    branches:
      -  main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -  name: repository test
       uses: actions/checkout@v4
    -  name: list
       run: | 
         echo "verify the following details" $APP_NAME $ENVIRONMENT $COMPANY
       env:
         APP_NAME: test app
         ENVIRONMENT: test environment
    -  name: date
       run: date
