name: test2
on:
  push:
    branches:
      -main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
        uses: actions/checkout@v4
    -name: list
      run: ls
    -name: date
      run: date
      
